#!/usr/bin/env sh
set -e;

if test $# -lt 1; then
	echo "Usage: tear git-url"
	exit 1
fi

mkdir -p $TEAR_DIR/packages $TEAR_DIR/bin $TEAR_DIR/lib

cd $TEAR_DIR/packages

if test $# -lt 2; then
	fido $1 master
else
	fido $@
fi

cd $TEAR_DIR

#for f in $FIDO_CLONED_TO_DIR/bin/* $FIDO_CLONED_TO_DIR/lib; do
	#echo $f
#done
