#!/usr/bin/env ruby
require 'fileutils'

include FileUtils
include FileUtils::Verbose

if ENV["TEARDIR"].nil?
		abort "You need to set $TEARDIR"
end

if ARGV.size == 0
		abort "Usage: #{$0} dir"
end

TearDir = File.expand_path(ENV["TEARDIR"])

mkdir_p TearDir + "/bin"
mkdir_p TearDir + "/lib"

cd ARGV[0] do
		Dir["{lib,bin}/*"].each do |file|
				to = File.join(TearDir, file)
				next if File.file?(to)
				ln_s File.expand_path(file), to
		end
end
